cache: false
wishlist:
  - https://www.dekudeals.com/wishlist/yc4tqb7mt7
alert:
  sale: true
  discountPrice: 3
  discountPercentage: 80
game:
  - name: Super Mario Odyssey
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: Mario Kart 8 Deluxe
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: Super Mario 3D World + Bowser’s Fury
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: Mario Party Superstars
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: New Super Mario Bros. U Deluxe
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: 'The Legend of Zelda: Breath of the Wild'
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: 'The Legend of Zelda: Link’s Awakening'
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: 'The Legend of Zelda: Skyward Sword HD'
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: Super Smash Bros. Ultimate
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: Pokémon Sword
    alert:
      discountPrice: 10
      discountPercentage: 25
  - name: Ori and the Will of the Wisps
    alert:
      discountPrice: 10
      discountPercentage: 50
  - name: Xenoblade Chronicles Definitive Edition
    alert:
      discountPrice: 10
      discountPercentage: 50
  - name: 'Fire Emblem: Three Houses'
    alert:
      discountPrice: 10
      discountPercentage: 50
  - name: 'Diablo III: Eternal Collection'
    alert:
      discountPrice: 10
      discountPercentage: 50
  - name: Luigi’s Mansion 3
    alert:
      discountPrice: 10
      discountPercentage: 50
  - name: Minecraft
    alert:
      discountPrice: 10
      discountPercentage: 50
  - name: Immortals Fenyx Rising
    alert:
      discountPrice: 15
      discountPercentage: 70
  - name: Children of Morta
    alert:
      discountPrice: 7
      discountPercentage: 70
mail:
  host: riscue.xyz
  port: 465
  username: eshop-discount@riscue.xyz
  password: 6thGNfl33dzhbBVVcFjmS20iR9cYMEcN3i71u0mjL1Pq3sjmK
  to:
    - ibrahim@ibrahimakyel.com
